### ISSUE TITLE
Using this loader along with script-loader and sourcemaps

### ISSUE THREAD

**Issue by maxgalbu** [bestander/uglify-loader#8]
Hi,
sorry for opening an issue which is not actually an issue :) I'm currently using script-loader to pack my javascript into the webpack file, and generate a sourcemap using webpack. Here's the config:

```
var config = {
    entry: {
      news: './news.js'
    },
    devtool: 'source-map',
    debug: true,
    output: {
      path: './bin',
      filename: '[name].js',
      sourceMapFilename: "[file].map.js"
    },
  };
```

This generates two files, `news.js` and `news.js.map.js`. The "packed" script in `news.js` are not minified, so I found your project which seems to do what i need, but after packing the scripts with "script-loader" and "uglify-loader", the sourcemap from webpack refers to the minified files, and i'm confused on how to use the sourcemap generated by uglify (https://github.com/bestander/uglify-loader/blob/cda8249253bf2bd1a5ff2273354ad41ca57cf6af/index.js#L21-L24)

Here's an excerpt from my news.js file:

```
require("script!uglify!../../polling.js");
require("script!uglify!../../normalize.js");
```

So, my request is: how can I have the sourcemap of the un-uglified code? Do i need to start using the uglify one? How can i put all of it in a single file like webpack does?

**Comment by bestander** [comment]
Hi @maxgalbu, sorry but it's been a while since I played with webpack source maps and I remember it being non obvious and I don't have an answer for this from the top of my head now.

I would recommend you to search/ask on StackOverflow http://stackoverflow.com/questions/tagged/webpack, source maps in stacked loader scheme should be a common issue.

I'll close this for now because don't know what to add :)
